export const CITY_MAP = {
  seoul: "서울",
  busan: "부산",
  incheon: "인천",
  gwangju: "광주",
  dajeun: "대전",
  ulsan: "울산",
  sejong: "세종",
  gyeonggido: "경기",
  gangwon: "강원",
  degu: "대구",
  gwangju: "광주",
  chungcheong: ["충북", "충남"],
  jeollado: ["전남", "전북"],
  gyeongsangdo: ["경남", "경북"],
  jeju: "제주",
};
